# .github/workflows/deploy.yml
name: Deploy Static Site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install pug-cli -g
      - run: pug ./templates -o ./dist  # Pug → HTML
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./root
